cinst 7zip
cinst adobereader
cinst ConEmu
cinst f.lux
cinst Firefox
cinst git
cinst GitHub
cinst GoogleChrome
cinst javaruntime
cinst kdiff3
cinst linqpad
cinst mozbackup
cinst nodejs
cinst notepadplusplus
cinst NuGet.CommandLine
cinst python
cinst RoboMongo
cinst ruby
cinst sharex
cinst skype
cinst slack
cinst SourceTree
cinst spotify
cinst sysinternals
cinst teamviewer
cinst treesizefree
cinst virtualbox
cinst VirtualBox.ExtensionPack
cinst winscp
